
class Param:
    def __init__(self, CLUSTERS, CLUST_SIZE, DAYS, INFECTION_TIME, DEATH_RATE, INFECT_RATE, 
            MIGRATIONS_PER_DAY, FEAR_RATE, HEALTHCARE_CAPACITY):
        self.CLUSTERS = CLUSTERS
        self.CLUST_SIZE = CLUST_SIZE
        self.DAYS = DAYS
        self.INFECTION_TIME = INFECTION_TIME
        self.DEATH_RATE = DEATH_RATE
        self.INFECT_RATE = INFECT_RATE
        self.MIGRATIONS_PER_DAY = MIGRATIONS_PER_DAY
        self.FEAR_RATE = FEAR_RATE
        self.HEALTHCARE_CAPACITY = HEALTHCARE_CAPACITY
